# Generated by Django 5.1.6 on 2025-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_user_id_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
