# Generated by Django 5.1.6 on 2025-02-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
