# Generated by Django 5.1.6 on 2025-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
