# Generated by Django 5.1.6 on 2025-02-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_anagrafica_email_anagrafica_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagrafica',
            name='appointment',
        ),
    ]
