# Generated by Django 5.1.6 on 2025-02-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_remove_anagrafica_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
