# Generated by Django 5.1.6 on 2025-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_anagrafica_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
