# Generated by Django 5.1.6 on 2025-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_appointment_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
